name: Write Now
favicon: null
layout_spectrum: 0.09322281344793737
typography_spectrum: 0.7927348862867802
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8503442355431616
  lightness: 0.8806882642675191
  saturation: 0.8270865140948445
  rhythmicContrast: 0.35303335008211434
purpose: []
